# Generated by Django 3.2.4 on 2021-06-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='one_time_use',
            field=models.BooleanField(default=True),
        ),
    ]
